### ISSUE TITLE
language issue

### ISSUE THREAD

**Issue by cattyngmd** [yer7700/discord-self-bot-crasher#3]
язык говно, жду фикс

**Comment by yer7700** [comment]
ЗДРАВСТВУЙТЕ, CATTYNDMG, ПРОШУ ПРОЩЕНИЯ ЧЕМ Я МОГУ ПОМОЧЬ, ЯЗЫК ИЗМЕНИМ В БЛИЖАЙШИЕ 2 ВЕКА

**Comment by Softik777** [comment]
пошли на хуй?

**Comment by DiOnFire** [comment]
> язык говно, жду фикс

Манимод с ратом, жду фикс

**Comment by ZI7PPER** [comment]
исью кэн би клоусед, так то

**Comment by DiOnFire** [comment]
мда
